---
title: "Untitled"
output: html_document
---

Idk what this means:
```{r}
knitr::opts_chunk$set(echo = TRUE)
```


Import what we need: 
```{r}
#source("summarySEWithin.Rmd")
library(ggplot2)
library(plotly)
library(broom)
library(car)
library(olsrr)
library(ppcor)
library(rstatix)
library(dplyr)

rm(list = ls()) 

pathnames <- list.files(pattern="[.]R$", path="/Users/carolinemyers/Desktop/CM_Experiments/Functions/Data analysis", full.names=TRUE);
sapply(pathnames, FUN=source);
rm(pathnames)


```


```{r}

library(readxl)
cleanedDataAllIncluded <- read_excel("/Users/carolinemyers/Desktop/CM_Experiments/IN_PROGRESS/fire/FlSearchV2/FLSearch_v2.1.7_PREREG/analysis/cleanedDataAllIncluded.xlsx")

rawdata <- data.frame(cleanedDataAllIncluded)

dataFrame <- data.frame((rawdata[c("subNum", "set_size","target_present","target","rt","correctNumeric")]))
```



Let's clean this up a bit. THIS WORKS!


```{r}
library(dplyr)
TP_Correct_All <-subset(dataFrame, target_present == "true" & correctNumeric == 1)

TP_Correct_All_Formatted <- TP_Correct_All %>%
  group_by(subNum,target,set_size) %>%
  summarise(medianRT = median(rt), sd = sd(rt),n = n())

TP_Correct_All__BySub_Formatted <- TP_Correct_All %>%
  group_by(subNum) %>%
  summarise(medianRT = median(rt), sd = sd(rt),n = n())

nIncluded <- dim(TP_Correct_All__BySub_Formatted)[1]

```


```{r}

TP_Correct_All_Formatted$target <- factor(TP_Correct_All_Formatted$target)
TP_Correct_All_Formatted$set_size <- factor(TP_Correct_All_Formatted$set_size, levels=c(4,5,6,7,8))




datac <- summarySEwithin(TP_Correct_All_Formatted, measurevar="medianRT", withinvars=c("set_size","target"), idvar="subNum")
datac

library(ggplot2)
ggplot(datac, aes(x= set_size, y=medianRT, fill=target)) +
    geom_bar(position=position_dodge(.9), colour="black", stat="identity") +
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=medianRT-ci, ymax=medianRT+ci)) +
   # coord_cartesian(ylim=c(40,46)) +
 # ylim=c(ymin, ymax) + 
  
  
   labs(title = "Median RT on correct target present trials (n = 34)", x = "set size", y = "median RT", color = "Legend Title\n") +
  scale_color_manual(labels = c("target reverse", "target forward"), values = c("#CCCCCC","#FFFFFF")) +
 scale_fill_manual(values=c("#CCCCCC","#FFFFFF"),labels = c("Target burns in reverse", "Target burns forward")) +
    theme_bw() 
  #  scale_y_continuous(breaks=seq(1:100)) +
    theme_bw() 
    #geom_hline(yintercept=38) 

an2 <- aov(medianRT ~ (set_size * target) + Error(subNum/(set_size * target)), TP_Correct_All_Formatted)

summary(an2)

TP_Correct_All_Formatted2 <- data.frame(TP_Correct_All_Formatted)

library(rstatix)


res.aov <- anova_test(
  data = TP_Correct_All_Formatted2, dv = medianRT, wid = subNum,
  within = c(set_size, target)
  )
get_anova_table(res.aov)



```

Paired t test
```{r}
library(dplyr)
TP_Correct_All_Formatted_Paired <- TP_Correct_All %>%
  group_by(subNum,target) %>%
  summarise(medianRT = median(rt), sd = sd(rt),n = n())




TP_Correct_All_Formatted_Paired $target <- factor(TP_Correct_All_Formatted_Paired $target)


forward <- subset(TP_Correct_All_Formatted_Paired ,  target == "img/Fire_Up_Target.gif", medianRT,
                 drop = TRUE)
# subset weight data after treatment
reverse <- subset(TP_Correct_All_Formatted_Paired,target == "img/Fire_Down_Target.gif", medianRT,
                 drop = TRUE)


library("writexl")
write_xlsx(TP_Correct_All_Formatted_Paired ,"/Users/carolinemyers/Desktop/CM_Experiments/IN_PROGRESS/fire/FlSearchV2/FLSearch_v2.1.7_PREREG/analysis/datalongPaired.xlsx")



PairedVertical <- data.frame(forward,reverse)
PairedVertical$Diff <- PairedVertical$forward - PairedVertical$reverse



# Plot paired data

#install.packages("PairedData")
library(PairedData)
pd <- paired(forward, reverse)
plot(pd, type = "profile") + theme_bw()


t.test(forward, reverse, paired = TRUE, alternative = "two.sided")

mean(forward)
mean(reverse)                              
```

Now let's take a look at accuracy. 






Now let's take a look at accuracy. 

```{r}
library(dplyr)
TP_All <-subset(dataFrame, target_present == "true")

TP_All_Formatted <- TP_All %>%
  group_by(subNum,target,set_size) %>%
  summarise(accuracy = mean(correctNumeric), sd = sd(correctNumeric),n = n())



```

```{r}
detach("package:dplyr", unload=TRUE)
TP_All_Formatted$target <- factor(TP_All_Formatted$target)
TP_All_Formatted$set_size <- factor(TP_All_Formatted$set_size, levels=c(4,5,6,7,8))




datac <- summarySEwithin(TP_All_Formatted, measurevar="accuracy", withinvars=c("set_size","target"), idvar="subNum")
datac

library(ggplot2)
ggplot(datac, aes(x= set_size, y=accuracy, fill=target)) +
    geom_bar(position=position_dodge(.9), colour="black", stat="identity") +
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=accuracy-ci, ymax=accuracy+ci)) +
 
   labs(title = "Accuracy on target present trials, rotated 90°\n", x = "set size", y = "PC", color = "Legend Title\n") +
  scale_color_manual(labels = c("target reverse", "target forward"), values = c("#CCCCCC","#FFFFFF")) +
 scale_fill_manual(values=c("#CCCCCC","#FFFFFF"),labels = c("Target burns in reverse", "Target burns forward"))
   
 theme_bw() 
    #geom_hline(yintercept=38) 

an2 <- aov(accuracy ~ (set_size * target) + Error(subNum/(set_size * target)),TP_All_Formatted)

summary(an2)

TP_All_Formatted2 <- data.frame(TP_All_Formatted)

library(rstatix)


res.aov <- anova_test(
  data = TP_All_Formatted2, dv = accuracy, wid = subNum,
  within = c(set_size, target)
  )
get_anova_table(res.aov)

```


#ACC OLD
```{r}
library(dplyr)
TP_All <-subset(dataFrame, target_present == "true")

TP_All_Formatted <- TP_All %>%
  group_by(subNum,target,set_size) %>%
  summarise(accuracy = mean(correctNumeric), sd = sd(correctNumeric),n = n())



```

```{r}

TP_All_Formatted$target <- factor(TP_All_Formatted$target)
TP_All_Formatted$set_size <- factor(TP_All_Formatted$set_size, levels=c(4,5,6,7,8))




datac <- summarySEwithin(TP_All_Formatted, measurevar="accuracy", withinvars=c("set_size","target"), idvar="subNum")
datac

library(ggplot2)
ggplot(datac, aes(x= set_size, y=accuracy, fill=target)) +
    geom_bar(position=position_dodge(.9), colour="black", stat="identity") +
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=accuracy-ci, ymax=accuracy+ci)) +
   # coord_cartesian(ylim=c(40,46)) +
 # ylim=c(ymin, ymax) + 
  scale_fill_manual(values=c("#CCCCCC","#FFFFFF")) +
  #  scale_y_continuous(breaks=seq(1:100)) +
    theme_bw() 
    #geom_hline(yintercept=38) 

an2 <- aov(accuracy ~ (set_size * target) + Error(subNum/(set_size * target)),TP_All_Formatted)

summary(an2)

TP_All_Formatted2 <- data.frame(TP_All_Formatted)

library(rstatix)


res.aov <- anova_test(
  data = TP_All_Formatted2, dv = accuracy, wid = subNum,
  within = c(set_size, target)
  )
get_anova_table(res.aov)



```



```{r}

## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}



## Summarizes data, handling within-subjects variables by removing inter-subject variability.
## It will still work if there are no within-S variables.
## Gives count, un-normed mean, normed mean (with same between-group mean),
##   standard deviation, standard error of the mean, and confidence interval.
## If there are within-subject variables, calculate adjusted values using method from Morey (2008).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   withinvars: a vector containing names of columns that are within-subjects variables
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySEwithin <- function(data=NULL, measurevar, betweenvars=NULL, withinvars=NULL,
                            idvar=NULL, na.rm=FALSE, conf.interval=.95, .drop=TRUE) {

  # Ensure that the betweenvars and withinvars are factors
  factorvars <- vapply(data[, c(betweenvars, withinvars), drop=FALSE],
    FUN=is.factor, FUN.VALUE=logical(1))

  if (!all(factorvars)) {
    nonfactorvars <- names(factorvars)[!factorvars]
    message("Automatically converting the following non-factors to factors: ",
            paste(nonfactorvars, collapse = ", "))
    data[nonfactorvars] <- lapply(data[nonfactorvars], factor)
  }

  # Get the means from the un-normed data
  datac <- summarySE(data, measurevar, groupvars=c(betweenvars, withinvars),
                     na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Drop all the unused columns (these will be calculated with normed data)
  datac$sd <- NULL
  datac$se <- NULL
  datac$ci <- NULL

  # Norm each subject's data
  ndata <- normDataWithin(data, idvar, measurevar, betweenvars, na.rm, .drop=.drop)

  # This is the name of the new column
  measurevar_n <- paste(measurevar, "_norm", sep="")

  # Collapse the normed data - now we can treat between and within vars the same
  ndatac <- summarySE(ndata, measurevar_n, groupvars=c(betweenvars, withinvars),
                      na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Apply correction from Morey (2008) to the standard error and confidence interval
  #  Get the product of the number of conditions of within-S variables
  nWithinGroups    <- prod(vapply(ndatac[,withinvars, drop=FALSE], FUN=nlevels,
                           FUN.VALUE=numeric(1)))
  correctionFactor <- sqrt( nWithinGroups / (nWithinGroups-1) )

  # Apply the correction factor
  ndatac$sd <- ndatac$sd * correctionFactor
  ndatac$se <- ndatac$se * correctionFactor
  ndatac$ci <- ndatac$ci * correctionFactor

  # Combine the un-normed means with the normed results
  merge(datac, ndatac)
}




## Norms the data within specified groups in a data frame; it normalizes each
## subject (identified by idvar) so that they have the same mean, within each group
## specified by betweenvars.
##   data: a data frame.
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   na.rm: a boolean that indicates whether to ignore NA's
normDataWithin <- function(data=NULL, idvar, measurevar, betweenvars=NULL,
                           na.rm=FALSE, .drop=TRUE) {
    library(plyr)

    # Measure var on left, idvar + between vars on right of formula.
    data.subjMean <- ddply(data, c(idvar, betweenvars), .drop=.drop,
     .fun = function(xx, col, na.rm) {
        c(subjMean = mean(xx[,col], na.rm=na.rm))
      },
      measurevar,
      na.rm
    )

    # Put the subject means with original data
    data <- merge(data, data.subjMean)

    # Get the normalized data in a new column
    measureNormedVar <- paste(measurevar, "_norm", sep="")
    data[,measureNormedVar] <- data[,measurevar] - data[,"subjMean"] +
                               mean(data[,measurevar], na.rm=na.rm)

    # Remove this subject mean column
    data$subjMean <- NULL

    return(data)
}
```



