---
title: "EAB Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pracma)
library(ggplot2)
library(plotly)
library(broom)
library(car)
library(olsrr)
library(ppcor)
library(rstatix)
library(dplyr)
library(BayesFactor)
library(writexl)
library(gtools)
library(PairedData)
library(here)
library(ggthemes)
library(extrafont)
library(gridExtra)
library(officer)
library(rvg)

rm(list = ls()) 




pathnames <- list.files(pattern="[.]R$", path="/Users/carolinemyers/Desktop/CM_Experiments/Packages/CM_Functions/Data analysis", full.names=TRUE);
sapply(pathnames, FUN=source);
rm(pathnames)

getwd()



```

```{r}

expName = "EAB 4.1.6"
exclusionCriteria <- .8

```



```{r}
getwd()
setwd('../data')
getwd()
files <- list.files()

rawDataList <- list()
cleanedDataList <- list()
feedbackQ <- list()

for (ii in 1:length(files)) {
#ii <- 1
  currentRawData <- read.csv(file.path(files[ii])) #read in the data
  #feedbackQ[ii] <- currentRawData$response[length(currentRawData$subject_id)] #get subject feedback
  currentRawData <- currentRawData[currentRawData$test_part == 'response' & currentRawData$phase == 'test', ]  #keep only testing trials
  prolificPID <- currentRawData$subject_id[length(currentRawData$subject_id)] #get the subject's prolific ID
  subNo <- repmat(ii, length(currentRawData$subject_id),1) #assign a number to the subject
 trial <-1:length(currentRawData$subject_id) 
 currentRawData <-   cbind.data.frame(prolificPID,subNo,trial,currentRawData)
 
#Get rid of trials < 200 ms!!
#currentRawData$rt <- as.numeric(currentRawData$rt)
#currentRawData <- subset(currentRawData, rt > 200)

 
currentRawData$correctNumeric <- NA

for (jj in 1:nrow(currentRawData)) {
 if  (currentRawData$correct[jj] == 'true') {
   currentRawData$correctNumeric[jj] = 1
 } else if (currentRawData$correct[jj] == 'false') {
   currentRawData$correctNumeric[jj] = 0
 }
}


currentRawData$included <- 1



#Remove unnecessary columns  
currentRawData <- subset(currentRawData, select = -c(success,timeout,failed_images, failed_audio, failed_video,trial_type, trial_index,time_elapsed, internal_node_id,subject_id, study_id,session_id,stimulus))

rawDataList[[ii]] <-  (currentRawData[,1:ncol(currentRawData)])


if (rawDataList[[ii]]$included[[1]] == 1) {
  cleanedDataList[[ii]]  <- rawDataList[[ii]]
}
if (rawDataList[[ii]]$included[[1]] == 0) {
  cleanedDataList[[ii]]  <- NULL
}
cleanedDataList<-cleanedDataList[!sapply(cleanedDataList,is.null)]


}

rawData <- do.call(rbind, rawDataList)
cleanedData <- do.call(rbind, cleanedDataList)
rm(list = c('ii','jj','trial','files','subNo','prolificPID','currentRawData','exclusionCriteria')) 
```

## Get correct target present trials, filter and factor them. 

```{r}
#write_xlsx(cleanedData,"cleanedDatur.xlsx")

#Summarizing each subject
subjectSummary <- cleanedData %>% 
  group_by(subNo) %>% 
  summarise(overallAccuracy = mean(cleanedData$correctNumeric), sd = sd(rt),n = n())


nIncluded <- nrow(subjectSummary)

cleanedData$rt <- as.numeric(cleanedData$rt)

# Now we're going to need to compare neutral and fire trials on lag = 2






# Finding correct target present trials
lag2TrialsSummary <- cleanedData %>% 
  group_by(subNo,t1_type) %>% 
  filter(lag == 2) %>%
  summarise(mean = mean(correctNumeric), sd = sd(correctNumeric),n = n())
lag2TrialsSummary$t1_type <- factor(lag2TrialsSummary$t1_type)


# Finding correct target present trials
lag2Trials <- cleanedData %>% 
  group_by(subNo,t1_type) %>% 
  filter(lag == 2) 

lag2Trials$t1_typef <- factor(lag2Trials$t1_type)


# get neutral and fire trials
lag2Trials <- cleanedData %>% 
  group_by(subNo,t1_type) %>% 
  filter(lag == 2) 




# Finding JUST target present trials (for accuracy later.)
justTargetPresentTrials <- cleanedData %>% 
  group_by(subNo,target,set_size) %>% 
  filter(target_present == "true") %>%
  summarise(meanAcc = mean(correctNumeric), sdAcc = sd(correctNumeric),n = n())

justTargetPresentTrials$target <- factor(justTargetPresentTrials$target)
justTargetPresentTrials$set_size <- factor(justTargetPresentTrials$set_size, levels=c(4,5,6,7,8))


```

Analyze median reaction time for target present correct trials. 
```{r}

correctTargetPresentTrials <- data.frame(correctTargetPresentTrials)
datac <- summarySEwithin(correctTargetPresentTrials, measurevar="medianRT", withinvars=c("set_size","target"), idvar="subNo")
datac

datad <- datac %>% 
  mutate(target2 = if_else(target == 	'img/Fire_Down_Target.gif', "bDown", "aUp"))





#library(ggplot2)
p <- ggplot(datad, aes(x= set_size, y=medianRT, fill=target2)) +
    geom_bar(position=position_dodge(.9), colour="white", stat="identity") +
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=medianRT-ci, ymax=medianRT+ci)) +
  #ggtitle(paste0(expName,"\n Median RT on correct target present trials (n = ",nIncluded,")\n")) +
   ggtitle(paste0("Experiment 1 (n = ",nIncluded,") \n Median RT ")) +
   labs(x = "set size", y = "median RT", color = "Legend Title\n") +
 scale_fill_manual(values=c("#980D00","#DC965A"),labels = c("Fire burns up (normally)", "Fire burns down (reverse)")) +
    theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())


#Export to powerpoint
p_dml <- rvg::dml(ggobj = p)
doc <- read_pptx()
doc <- add_slide(doc, 'Title and Content', 'Office Theme')
doc <- ph_with(doc,p_dml, location = ph_location_fullsize() )  
print(doc, target = 'plot.pptx')
#ggplotly(p)
# Example usage:
#grid.arrange(Bar,(Bar + scale_fill_Publication() +theme_Publication()),nrow=1)

p <- grid.arrange((p + scale_fill_Publication() +theme_Publication() +scale_fill_manual(values=c("#c8945c","#980D00"),labels = c("Fire burns up (normally)", "Fire burns down (reverse)"))),nrow=1)




#p + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())


an2 <- aov(medianRT ~ (set_size * target) + Error(subNo/(set_size * target)), correctTargetPresentTrials)
summary(an2)

res.aov <- anova_test(
  data = correctTargetPresentTrials, dv = medianRT, wid = subNo,
  within = c(set_size, target)
  )
get_anova_table(res.aov)

# other reasonable colors: 
#ce7e00
```

```{r}


datad <- summarySEwithin(PairedRT, measurevar="medianRT", withinvars="target", idvar="subNo")
datad

#library(ggplot2)
ggplot(datad, aes(x= target, y=medianRT)) +
    geom_bar(position=position_dodge(.9), colour="black", stat="identity") +
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=medianRT-ci, ymax=medianRT+ci)) +
   ggtitle(paste0("Experiment 1 (n = ",nIncluded,") \n Median RT ")) +
   labs(x = "set size", y = "median RT", color = "Legend Title\n") +
 scale_fill_manual(values=c("#CCCCCC","#FFFFFF"),labels = c("Fire burns down (reverse)", "Fire burns up (normal)")) +
    theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

#library(gridExtra)
#p + theme_economist()
#Bar <- ggplot(mtcars, aes(factor(carb),fill=factor(carb))) + geom_bar(alpha=0.7) + labs(title="Bar Plot")

# Example usage:
#grid.arrange(Bar,(Bar + scale_fill_Publication() +theme_Publication()),nrow=1)




```



Paired t-test on RT 


```{r}
 
library(dplyr)
library(rvg)

PairedRT <- cleanedData %>% 
  group_by(subNo,target) %>% 
  filter(correct == "true",target_present == "true") %>%
  summarise(medianRT = median(rt), sd = sd(rt),n = n())

PairedRT$target <- factor(PairedRT$target)



fireDownRT <- subset(PairedRT ,  target == "img/Fire_Down_Target.gif", medianRT,
                 drop = TRUE)
fireUpRT <- subset(PairedRT,target == "img/Fire_Up_Target.gif", medianRT,
                 drop = TRUE)
library(plotrix)
#get standard error of difference
RTDiffs <- fireUpRT - fireDownRT
stdErrorDiff <- std.error(RTDiffs)

#save t test stats
fireV2_Original_RT_paired = data.frame(fireDownRT,fireUpRT)
write_xlsx(fireV2_Original_RT_paired,paste0(expName,"_pairedT.xlsx"))

# Plot paired data

library(PairedData)
pd <- paired(fireUpRT, fireDownRT)
xx <- plot(pd, type = "profile") +
    ggtitle(paste0(expName,"\n Median RT on correct target present trials (n = ",nIncluded,")\n")) +
theme_bw()
library(tidyverse)
ggplotly(xx)





ttestRes <- t.test(fireUpRT, fireDownRT, paired = TRUE, alternative = "two.sided")
ttestBF(fireUpRT, fireDownRT, paired = TRUE, alternative = "two.sided") 

ttestRes


paste0(mean(fireDownRT)," mean RT: fire down") 
paste0(mean(fireUpRT)," mean RT: fire up") 




## Let's briefly check on that outlier

fireV2_Original_RT_paired_NO_OUTLIER <- fireV2_Original_RT_paired[-c(32), ]

fireDownRT_NO_OUTLIER <- fireV2_Original_RT_paired_NO_OUTLIER$fireDownRT
fireUpRT_NO_OUTLIER <- fireV2_Original_RT_paired_NO_OUTLIER$fireUpRT


ttestRes2 <- t.test(fireDownRT_NO_OUTLIER, fireUpRT_NO_OUTLIER, paired = TRUE, alternative = "two.sided")
ttestRes2





library(PairedData)
pd <- paired(fireUpRT_NO_OUTLIER, fireDownRT_NO_OUTLIER)
xx <- plot(pd, type = "profile") +
    ggtitle(paste0(expName,"\n Median RT on correct target present trials, outlier removed (n = ",nIncluded - 1,")\n")) +
theme_bw()
library(tidyverse)
ggplotly(xx)


```

Visualizing paired t test 2
```{r}
knitr::opts_chunk$set(echo = TRUE)

library(ggpubr)
library(rstatix)
library(tidyverse)

RTdiff <- fireUpRT - fireDownRT
aa <-rep('a',each=34)
RTdiff <- data.frame(RTdiff,aa)

tTestCI <- ttestRes$conf.int

bxp <- ggpaired(PairedRT, x = "target", y = "medianRT", 
         order = c("before", "after"),
         ylab = "Median RT", xlab = "Target fire")


#library(ggplot2)
ggplot(RTdiff, aes(x = 'aa', y=RTdiff))  +
    geom_bar(position=position_dodge(.9), colour="black", stat="identity")

+
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=ttestRes$conf.int[1], ymax=ttestRes$conf.int[2]))

#library(ggplot2)
p <- ggplot(datac, aes(x= set_size, y=medianRT, fill=target)) +
    geom_bar(position=position_dodge(.9), colour="black", stat="identity") +
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=medianRT-ci, ymax=medianRT+ci)) 
```
try 3
```{r}

library(ggplot2)
library(plyr)
theme_set(theme_bw()+theme(panel.margin=grid::unit(0,"lines")))
n = 20
effect = 5 
set.seed(4711)
glu0 = rnorm(n,120,30)
glu1 = glu0 + rnorm(n,effect,7)
dt = data.frame(patient = rep(paste0("P",10:(9+n))),              
                treatment = rep(c("A","B"), each=n),glucose = c(glu0,glu1))



dt1 = ddply(PairedRT,.(treatment), function(x){
  data.frame(glucose = mean(x$glucose), se = sqrt(var(x$glucose)/nrow(x)) )})

tt = t.test(glucose~treatment,paired=TRUE,data=dt,conf.int=TRUE)
dt2 = data.frame(diff = -tt$estimate,low=-tt$conf.int[2], up=-tt$conf.int[1])
p = paste("p =",signif(tt$p.value,2))



RTdiff <- fireUpRT - fireDownRT
aa <-rep('a',each=34)
RTdiff <- data.frame(RTdiff,aa)

png(height=300,width=300)
ggplot(PairedRT, aes(x=target, y=medianRT, fill=target))+      
  geom_bar(stat="identity")+  
  geom_errorbar(aes(ymin=medianRT-se, ymax=medianRT+se),size=1., width=0.3)+
  geom_text(aes(1.5,150),label=p,size=6)




# Main analysis plot
ggplot(PairedRT, aes(y = medianRT, x = target, fill = "indianred3")) +
  theme(legend.position = "none")+
  scale_fill_manual(values=c("indianred3", "steelblue4")) +
  stat_summary(fun = mean, geom = "bar") +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width = .1) +
  ylab("Mean proportion of 'continuous silences longer' responses") +
  geom_hline(yintercept = 0.5, color = "steelblue4", ) +
  ylim(0,1)


```


```{r}
correctTargetPresentTrials <- data.frame(correctTargetPresentTrials)
datac <- summarySEwithin(correctTargetPresentTrials, measurevar="medianRT", withinvars="target", idvar="subNo")
datac

#library(ggplot2)
p <- ggplot(datac, aes(x= target, y=medianRT)) +
    geom_bar(position=position_dodge(.9), colour="black", stat="identity") +
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=medianRT-ci, ymax=medianRT+ci)) 
#+
  #ggtitle(paste0(expName,"\n Median RT on correct target present trials (n = ",nIncluded,")\n")) +
   ggtitle(paste0("Experiment 1 (n = ",nIncluded,") \n Median RT ")) +
   labs(x = "set size", y = "median RT", color = "Legend Title\n") +
 scale_fill_manual(values=c("#CCCCCC","#FFFFFF"),labels = c("Fire burns down (reverse)", "Fire burns up (normal)")) +
    theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

```


Now, paired t test for accuracy.

```{r}
PairedAcc <- cleanedData %>% 
  group_by(subNo,target) %>% 
  filter(target_present == "true") %>%
  summarise(meanAcc = mean(correctNumeric), sd = sd(correctNumeric),n = n())

PairedAcc$target <- factor(PairedAcc$target)


fireDownAcc <- subset(PairedAcc ,  target == "img/Fire_Down_Target.gif", meanAcc,
                 drop = TRUE)
fireUpAcc <- subset(PairedAcc,target == "img/Fire_Up_Target.gif", meanAcc,
                 drop = TRUE)


# Plot paired data
pd <- paired(fireDownAcc, fireUpAcc)
plot(pd, type = "profile") +
  ggtitle(paste0(expName,"\n Mean accuracy on target present trials (n = ",nIncluded,")\n")) +
theme_bw()

t.test(fireDownAcc, fireUpAcc, paired = TRUE, alternative = "two.sided")
ttestBF(fireDownAcc, fireUpAcc, paired = TRUE, alternative = "two.sided") 

mean(fireDownAcc)
mean(fireUpAcc)
```
Now ANOVA for accuracy
```{r}
justTargetPresentTrials <- data.frame(justTargetPresentTrials)
datad <- summarySEwithin(justTargetPresentTrials, measurevar="meanAcc", withinvars=c("set_size","target"), idvar="subNo")
datad

q <- ggplot(datad, aes(x= set_size, y=meanAcc, fill=target)) +
    geom_bar(position=position_dodge(.9), colour="black", stat="identity") +
    geom_errorbar(position=position_dodge(.9), width=.25, aes(ymin=meanAcc-ci, ymax=meanAcc+ci)) +

 # ggtitle(paste0(expName,"\n Mean accuracy on correct target present trials (n = ",nIncluded,")\n")) +
     ggtitle(paste0("Experiment 1 (n = ",nIncluded,") \n Accuracy")) +
   labs(x = "set size", y = "mean accuracy", color = "Legend Title\n") +
 scale_fill_manual(values=c("#CCCCCC","#FFFFFF"),labels = c("Fire burns down (reverse)", "Fire burns up (normal)")) #+
  #  theme_bw() 

an3 <- aov(meanAcc ~ (set_size * target) + Error(subNo/(set_size * target)), justTargetPresentTrials)

summary(an3)

res.aov <- anova_test(
  data = justTargetPresentTrials, dv = meanAcc, wid = subNo,
  within = c(set_size, target)
  )
get_anova_table(res.aov)

q <- grid.arrange((q + scale_fill_Publication() +theme_Publication() +scale_fill_manual(values=c("#980D00","#DC965A"),labels = c("Fire burns down (reverse)", "Fire burns up (normal)"))),nrow=1)

#To plot both together: 
# grid.arrange(p,(q + scale_fill_Publication() +theme_Publication()),nrow=1)


#p2 <- grid.arrange(q,(p + scale_fill_Publication() +theme_Publication() +scale_fill_manual(values=c("#980D00","#DC965A"),labels = c("Fire burns down (reverse)", "Fire burns up (normal)"))),nrow=1)

```